version: '3'
services:

  postgresdb:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - database-inf:/var/lib/postgresql/data/


volumes:
  database-inf:
